name: Notify Blox Fruit

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Lua
      uses: leafo/gh-actions-lua@v8

    - name: Run Lua script
      run: |
        lua your_script.lua
        
